# Generated by Django 3.0.3 on 2020-03-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_note',
            name='address',
        ),
        migrations.AddField(
            model_name='model_note',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_note',
            name='longtitude',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
