# Generated by Django 3.0.3 on 2020-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_model_note_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_note',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
