# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-25 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_auto_20200225_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_note',
            options={'ordering': ('publish',)},
        ),
    ]
